CREATE DATABASE ventas_jugos;

USE Ventas_jugos;

CREATE TABLE tb_producto(
CODIGO VARCHAR(10) NOT NULL, 
DESCRIPCION VARCHAR (100) NULL, 
SABOR VARCHAR (50) NULL,
TAMANO VARCHAR (50) NULL,
ENVASE VARCHAR(50) NULL, 
PRECIO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE tb_vendedor (
MATRICULA  VARCHAR (5) NOT NULL,
NOMBRE VARCHAR (100) NULL, 
BARRIO VARCHAR (50) NULL, 
COMISION FLOAT NULL, 
FECHA_ADMISION DATE NULL, 
DE_VACACIONES BIT(1) NULL,  
PRIMARY KEY (MATRICULA)
);

CREATE TABLE tb_cliente (
DNI VARCHAR (11) NOT NULL,
NOMBRE VARCHAR (100) NULL, 
DIRRECCION VARCHAR (150) NULL, 
BARRIO VARCHAR (50) NULL, 
CIUDAD VARCHAR (50) NULL, 
ESTADO VARCHAR (10) NULL, 
CP VARCHAR (10) NULL, 
FECHA_NACIMIENTO DATE NULL, 
EDAD SMALLINT NULL, 
SEXO VARCHAR (1) NULL, 
LIMITE_CREDITO FLOAT NULL, 
VOLUMEN_COMPRA FLOAT NULL, 
PRIMERA_COMPRA BIT (1) NULL,
PRIMARY KEY (DNI)
);

CREATE TABLE tb_items_facturas (
NUMERO VARCHAR (5) NOT NULL, 
CODIGO VARCHAR (10) NOT NULL, 
CANTIDAD INT NULL, 
PRECIO FLOAT NULL,
PRIMARY KEY (NUMERO, CODIGO)
);

CREATE TABLE tb_venta(
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE NULL,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY(NUMERO)
);

/* CREANDO RELACINES ENTRE TABLA DE CLIENTES Y VENDEDORES */
ALTER TABLE tb_venta ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY (DNI) REFERENCES tb_cliente(DNI);

ALTER TABLE tb_venta ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor(MATRICULA);

/* CAMBIANDO DE NOMBRE  */

ALTER TABLE tb_venta RENAME tb_factura;