USE empresa;

SELECT * FROM clientes;

CREATE DATABASE jugos_ventas;

-- RESTAURAMOS VALORES DE RESPALDO DE DB, MEDIANTE ASISTENTE PARA PODER INSERTAR A DATOS A EMPRESA

INSERT INTO items 
SELECT NUMERO, CODIGO_DEL_PRODUCTO AS CODIGO, CANTIDAD, PRECIO FROM jugos_ventas.items_facturas;

INSERT INTO facturas
SELECT  NUMERO, FECHA_VENTA AS FECHA, DNI, MATRICULA, IMPUESTO FROM jugos_ventas.facturas;

SELECT * FROM facturas F
INNER JOIN
items I 
ON F.NUMERO + I.NUMERO;