-- Se crea nueva DB
CREATE SCHEMA empresa;

USE empresa;
-- Creamos tablas
CREATE TABLE clientes (
DNI VARCHAR (11) NOT NULL,
NOMBRE VARCHAR (100) NULL,
DIRECCION VARCHAR (150),
BARRIO VARCHAR (50),
CIUDAD VARCHAR (50),
ESTADO VARCHAR (10),
CP VARCHAR (10),
FECHA_NACIMIENTO DATE,
EDAD SMALLINT,
SEXO VARCHAR (1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT,
PRIMARY KEY (DNI));

CREATE TABLE productos(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100),
SABOR VARCHAR(50),
TAMANAO VARCHAR (50),
ENVASE VARCHAR (50),
PRECIO FLOAT,
PRIMARY KEY (CODIGO));

CREATE TABLE facturas (
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE,
DNI VARCHAR (11) NOT NULL,
MATRICULA VARCHAR (5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY (NUMERO),
FOREIGN KEY (DNI) REFERENCES clientes(DNI),
FOREIGN KEY (MATRICULA) REFERENCES vendedores(MATRICULA)
);

CREATE TABLE items (
NUMERO VARCHAR (5) NOT NULL,
CODIGO VARCHAR (10) NOT NULL,
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY (NUMERO, CODIGO),
FOREIGN KEY (NUMERO) REFERENCES  facturas (NUMERO),
FOREIGN KEY (CODIGO) REFERENCES productos (CODIGO)
);